services:
  - type: web
    name: sales-agent
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 6060
      - key: DOMAIN
        value: sales-agent-76jb.onrender.com
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: PHONE_NUMBER_FROM
        sync: false
      - key: OPENAI_API_KEY
        sync: false
    autoDeploy: true
